# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [1]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [78]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.4122048  0.2983119  0.15246887 ... 0.17625736 0.89852045 0.05268522]
 [0.39932303 0.63249875 0.60380859 ... 0.43027202 0.21485013 0.50431308]
 [0.31538724 0.77357919 0.59532297 ... 0.99102989 0.66354894 0.79337096]
 ...
 [0.91334947 0.39533593 0.46150952 ... 0.06054957 0.34353549 0.52436021]
 [0.24526036 0.91845735 0.8394152  ... 0.90416027 0.56609547 0.40803862]
 [0.2154689  0.53446113 0.53642078 ... 0.10546637 0.7642417  0.31242317]]
[[0.26968657 0.64618974 0.40526426 ... 0.50962407 0.7641489  0.52287432]
 [0.52745365 0.03978511 0.76531027 ... 0.92796926 0.87493528 0.81640859]
 [0.50860754 0.27511497 0.71139021 ... 0.00937367 0.18423224 0.16175573]
 ...
 [0.98637492 0.01365812 0.62372835 ... 0.73595485 0.87834787 0.28766063]
 [0.91831294 0.32994535 0.65041894 ... 0.8002182  0.84794271 0.74857754]
 [0.98442263 0.38949383 0.95128632 ... 0.83505116 0.17724114 0.10694274]]


Без использования numpy

In [79]:
def mult(a, b):
    result = [[0 for _ in range(len(a[0]))] for _ in range(len(b))]


    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(b)):
                result[i][j] += a[i][k] * b[k][j]
    return result

C использованием numpy

In [80]:
def np_mult(a, b):
    result = np.dot(np.array(a), np.array(b))
    return result.tolist()

In [81]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 713 ms, sys: 0 ns, total: 713 ms
Wall time: 724 ms


In [6]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 240 µs, sys: 2.96 ms, total: 3.19 ms
Wall time: 4.87 ms


In [7]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.509903313490213e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [71]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.95606934 0.43115603 0.63194261] [0.64901822 0.64742748 0.88706716]


In [72]:
def scalar_product(a,b):
   s = sum(x * y for x, y in zip(a, b))
   return s

In [73]:
def np_scalar_product(a,b):
   s = np.dot(np.array(a), np.array(b))
   return s

In [74]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 24 µs, sys: 4 µs, total: 28 µs
Wall time: 31.7 µs
CPU times: user 46 µs, sys: 0 ns, total: 46 µs
Wall time: 50.3 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** ________________________________

операции Numpy реализованы на C языке, что позволяет избежать общих затрат на циклы в Python, косвенность указателей и динамическую проверку типов для каждого элемента. Увеличение скорости зависит от того, какие операции мы выполняем.

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [29]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
    matrix_np = np.array(a)
    n = len(matrix_np)
    main_diagonal_elements = matrix_np.diagonal()
    secondary_diagonal_elements = np.flip(matrix_np, axis=1).diagonal()
    even_main_diagonal_elements = main_diagonal_elements[::2]
    even_secondary_diagonal_elements = secondary_diagonal_elements[::2]
    total_even_diagonal_sum = np.sum(even_main_diagonal_elements) + np.sum(even_secondary_diagonal_elements)
    return total_even_diagonal_sum

In [30]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[3, 7, 8, 2, 3],
       [7, 1, 4, 5, 7],
       [9, 7, 1, 8, 7],
       [1, 1, 2, 2, 9],
       [2, 5, 9, 1, 8]])

In [32]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 166 µs, sys: 0 ns, total: 166 µs
Wall time: 172 µs


18

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [51]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(*A):
   X = np.array(A)
   cumsum_mat = np.cumsum(X, axis=1)
   row_indices = np.arange(1, X.shape[1] + 1)
   result = cumsum_mat / row_indices.reshape(1, -1)
   return result

In [52]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[0.42851733 0.50804513 0.48408783 0.34878391 0.69804191 0.58488292
 0.72649806 0.5573237  0.84035167 0.9491842  0.84458412 0.48755019
 0.13999906 0.36064532 0.91309293 0.36798309 0.47286981 0.75780128
 0.16532047 0.90770816 0.70664348 0.82909526 0.54621667 0.30525486
 0.93644759 0.5017816  0.56438977 0.20094482 0.52726167 0.82260162
 0.74940933 0.40036186 0.47058436 0.55971569 0.06543382 0.06633312
 0.29090297 0.58568734 0.15602771 0.8552597  0.35018503 0.92148419
 0.33566476 0.12016744 0.23988924 0.34218252 0.89409424 0.52017741
 0.97531723 0.89957021 0.63592032 0.93820441 0.69178141 0.42072523
 0.71733631 0.62487113 0.69340304 0.23490115 0.15198196 0.01886238
 0.86582813 0.58641731 0.675661   0.77234538 0.94362305 0.47644212
 0.77427315 0.4387332  0.05048487 0.7949225  0.83804407 0.80110024
 0.88376136 0.59073863 0.08665606 0.46939381 0.99777935 0.61298616
 0.13156475 0.37030439 0.46171055 0.43459652 0.55309588 0.57077276
 0.79143214 0.85371808 0.34418397 0.45482067 0.42804927 0.9593

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [39]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    change_indices = np.where(np.diff(a) != 0)[0]
    change_indices = np.concatenate(([0], change_indices + 1, [len(a)]))
    encoded_elements = a[change_indices[:-1]]
    counts = np.diff(change_indices)

    result = np.array([encoded_elements, counts])
    return result

In [40]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: user 141 µs, sys: 0 ns, total: 141 µs
Wall time: 154 µs


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [47]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    """
    param X: array
    """
    X_copy = copy(X)

    for i in range(1, len(X_copy), 2):
        X_copy[i] = a

    for i in range(0, len(X_copy), 2):
        X_copy[i] = X_copy[i] ** 3

    X_copy = X_copy[::-1]
    result = np.concatenate((X_copy, X_copy))
    return result

In [48]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 63 µs, sys: 0 ns, total: 63 µs
Wall time: 66.3 µs
